### ISSUE TITLE
make homepage attractive.

### ISSUE THREAD

**Issue by TheNinza** [TheNinza/javascript-projects#2]

**Comment by UnBeAtS01** [comment]
hey....hello i want to add  some something intersting in ur page

**Comment by TheNinza** [comment]
yeah sure... go ahead.. I assigned this to you @unbeat01

**Comment by arushi2715** [comment]
Hey @TheNinza 
Is this issue still open?

**Comment by TheNinza** [comment]
Creating new issue for this year and assign you that.. Closing this one
