### ISSUE TITLE
Make Homepage Attractive

### ISSUE THREAD

**Issue by TheNinza** [TheNinza/javascript-projects#4]

**Comment by arushi2715** [comment]
I would like to work on this.
Would you please assign this to me?

**Comment by TheNinza** [comment]
Sure @arushi2715 , go ahead

**Comment by ritesh423** [comment]
@TheNinza Can I work on this project?

**Comment by TheNinza** [comment]
hey @ritesh423 , Really appreciate your interest for this issue... But it is already assigned and doesn't need collaboration . And just saw your profile buddy.. A bright future awaits you..
